-- indexing/schema_pg.sql
-- Apply once via psql or build_index_pg.py before running the indexer.
-- Requires: PostgreSQL with pgvector extension (pre-installed in the Nuvolos Database app).
--
-- Usage (from Backend app terminal):
--   psql -h $PGHOST -U $PGUSER -d $PGDATABASE -f indexing/schema_pg.sql

CREATE EXTENSION IF NOT EXISTS vector;

-- Full source documents
CREATE TABLE IF NOT EXISTS rag_documents (
    doc_id        TEXT PRIMARY KEY,
    source_type   TEXT NOT NULL,
    title         TEXT,
    content       TEXT NOT NULL,
    metadata_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_rag_docs_source ON rag_documents(source_type);

-- Chunks: the unit of retrieval
-- text_tsv is auto-generated by PostgreSQL for full-text search (no manual insert needed)
CREATE TABLE IF NOT EXISTS rag_chunks (
    chunk_id          SERIAL PRIMARY KEY,
    doc_id            TEXT NOT NULL REFERENCES rag_documents(doc_id),
    source_type       TEXT NOT NULL,
    ord               INTEGER NOT NULL,
    header            TEXT NOT NULL,
    text              TEXT NOT NULL,
    ts_from           TEXT,
    ts_to             TEXT,
    participants_json TEXT,
    embedding         vector(768),
    text_tsv          tsvector GENERATED ALWAYS AS (
                          to_tsvector('english', coalesce(text, ''))
                      ) STORED
);

CREATE INDEX IF NOT EXISTS idx_rag_chunks_doc    ON rag_chunks(doc_id);
CREATE INDEX IF NOT EXISTS idx_rag_chunks_source ON rag_chunks(source_type);
CREATE INDEX IF NOT EXISTS idx_rag_chunks_ts     ON rag_chunks(ts_from, ts_to);
CREATE INDEX IF NOT EXISTS idx_rag_chunks_fts    ON rag_chunks USING GIN (text_tsv);

-- IVFFlat vector index is created by build_index_pg.py AFTER data is loaded
-- (IVFFlat needs existing data to compute cluster centroids).

-- Key/value store for index metadata
CREATE TABLE IF NOT EXISTS rag_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
